name: Deploy to H100

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      
      - name: Deploy with rsync
        env:
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASS" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude '.env' \
            --exclude 'venv/' \
            --exclude '__pycache__/' \
            --exclude '*.pyc' \
            --exclude 'server.log' \
            ./backend/ ubuntu@195.242.13.94:/home/ubuntu/backend/
          
      - name: Run deployment script
        env:
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no ubuntu@195.242.13.94 'cd /home/ubuntu/backend && \
          export GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}" && \
          source venv/bin/activate && \
          pip install groq && \
          bash deploy.sh'