name: Deploy to H100

on:
  push:
    branches: [ main ]
    paths:
      - 'src/backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      
      - name: Test Connection
        env:
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        run: sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no ubuntu@195.242.13.94 'echo "Connected successfully"'